# Generated by Django 5.0.1 on 2024-01-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('compliant', models.TextField(blank=True)),
            ],
        ),
    ]
