# Generated by Django 4.2.9 on 2024-02-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_menlist_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menlist',
            name='men',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.men'),
        ),
    ]
